---
# Display a summary

- name: Summary
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      Processable:
      {% for item in __process_list %}
        - {{ item }}
      {% endfor %}

      Multiple Top Folders in Archive (skip):
      {% for item in __skip_list %}
        - {{ item }}
      {% endfor %}

      Archive Missing:
      {% for item in __missing_list %}
        - {{ item }}
      {% endfor %}

      Total: {{ __process_list | length +  __skip_list | length + __missing_list | length }} =
        {{ __process_list | length }} (process) + {{ __skip_list | length
        }} (skip) + {{ __missing_list | length }} (missing)
