---
# Display a summary

- name: Summary
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      Processable:
      {% for item in __process_list %}
        - {{ item }}
      {% endfor %}

      Missing UUID:
      {% for item in __empty_uuid_list %}
        - {{ item }}
      {% endfor %}

      Multiple Top Folders in Archive (skip):
      {% for item in __skip_list %}
        - {{ item }}
      {% endfor %}

      Archive Missing:
      {% for item in __missing_list %}
        - {{ item }}
      {% endfor %}

      Total: {{ 
      __process_list | length 
      +  __skip_list | length 
      + __missing_list | length 
      + __empty_uuid_list | length 
      }} = {{ __process_list | length }} (processed) + {{ 
      __skip_list | length }} (skipped) + {{ 
      __missing_list | length }} (tarball missing) + {{ 
      __empty_uuid_list | length }} (empty uuid)
